services:
  - type: web
    name: mnist-app
    runtime: python
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt --no-cache-dir
    startCommand: |
      gunicorn app:app \
        --timeout 120 \
        --workers 1 \
        --threads 1 \
        --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
    healthCheckPath: /health
    plan: free